apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pony-pet
  namespace: mae
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: pony-pet
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: "java"
    workload-intent: code-analysis
spec:
  build:
    env:
    - name: BP_GRADLE_BUILD_FILE # workaround https://github.com/paketo-buildpacks/java/issues/423
      value: /foo
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_server_address
    value: ssh://git@github.com
  - name: gitops_ssh_secret
    value: gitops-ssh
  - name: gitops_repository_owner
    value: Mpluya
  - name: gitops_repository_name
    value: config-pet-clinic
  - name: gitops_branch
    value: main
  source:
    git:
      url: https://github.com/Mpluya/spring-pet-clinic.git
      ref:
        branch: main